#!/bin/sh

set -eu

TAXONOMY=""

TAXONOMY="$TAXONOMY TNHL TNHH TNLH TNLL"
TAXONOMY="$TAXONOMY TTHL TTHH TTLH TTLL"
TAXONOMY="$TAXONOMY TBHL TBHH TBLH TBLL"

TAXONOMY="$TAXONOMY SNHL SNHH SNLH SNLL"
TAXONOMY="$TAXONOMY STHL STHH STLH STLL"
TAXONOMY="$TAXONOMY SBHL SBHH SBLH SBLL"

TAXONOMY="$TAXONOMY LNHL LNHH LNLH LNLL"
TAXONOMY="$TAXONOMY LTHL LTHH LTLH LTLL"
TAXONOMY="$TAXONOMY LBHL LBHH LBLH LBLL"

INDEX=1
for category in $TAXONOMY
do
  echo "$category $INDEX"
  INDEX=$(( INDEX + 1 ))
done
